language: php

sudo: false

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0

matrix:
 allow_failures:
  - php: 7.0

env:
 global:
  - MOODLE_BRANCH=MOODLE_28_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci dev-master
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->local_redislock_redis_server = "tcp://127.0.0.1";'
  - moodle-plugin-ci add-config 'define("LOCAL_REDISLOCK_REDIS_LOCK_TEST", "true");'
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
